rxJava2 задание 2
raxander67/intensivStar pull request #2
Opened 2020-10-20 18:54 UTC by raxander67

2020-10-22 18:55 UTC, AndroidStudentClub requested changes
В целом неплохо, нужно уделить внимание
1) форматированию (код не отформатирован)
2) Избегать дублирования - используя дефолтные котлин-аргументы,extension- функции
Жду тогда zip

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/search/SearchFragment.kt
> +                    "ru",
Вот это можно в константы вынести, а еще лучше можно вынести прямо в ретрофит как дефолтные аргумент - тогда тут можно будет не повторять

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/search/SearchFragment.kt
> +                    BuildConfig.THE_MOVIE_DATABASE_API,
Да и это тоже можно прямо в методы интерфейса для ретрофита как дефолтный аргумент

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +            .subscribeOn(Schedulers.io())
SubscribeOn/ObserveOn чтобы не повторять лучше вынести в extension для Observable https://kotlinlang.org/docs/reference/extensions.html

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +            .subscribeOn(Schedulers.io())
Либо можно через compose переиспользовать еще. Вот тут в статье писал смотреть пункт 5
https://medium.com/androidschool-ru/5-%D1%87%D0%B0%D1%81%D1%82%D1%8B%D1%85-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA-%D0%BF%D1%80%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5-%D1%81-rxjava-1d734a3977ff

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +                    moviesList.forEach { m -> Timber.d(m.title.orEmpty()) }
Вот эта логика постоянно дублируется - можно вынести в функцию маппер - тогда можно будет переиспользовать

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +            .subscribeOn(Schedulers.io())
Можно в extension или compose

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/res/layout/list_item_movie.xml
> +        android:layout_height="35dp"
рекомендуется выносить все такие значение в ресурсы

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/res/layout/list_item_movie.xml
> +            android:paddingRight="16dp"
рекомендуется выносить все такие значение в ресурсы

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/res/layout/list_item_movie.xml
> +            android:textStyle="bold"
Тут можно стиль сделать - вынести в него все ресурсы и применить стиль к текс вью (примерно как это сделать https://devcolibri.com/unit/%D1%83%D1%80%D0%BE%D0%BA-4-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BC-styles-xml-%D0%B7%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D1%81%D1%82%D0%B2%D0%BE-%D1%81-textappeara-2/)

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/res/layout/list_item_movie.xml
> +    android:minHeight="72dp"
рекомендуется выносить все такие значение в ресурсы

2020-10-22 18:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/feed/FeedFragment.kt
> +            .subscribeOn(Schedulers.io())
Zip в следующей ДЗ будете использовать? Тогда все это можно будет 1 раз написать и не повторять 3 запроса

2020-10-26 08:08 UTC, raxander67 commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +            .subscribeOn(Schedulers.io())
Я перенёс в функцию getQueryToView. Эта функция повторяется теперь в двух файлах: TvShowsFragment.kt и FeedFragment.kt. 
Мой вопрос, наверно можно сделать абстрактный класс, что бы не повторять методы?

2020-10-26 16:46 UTC, raxander67 commented on app/src/main/res/layout/list_item_movie.xml
> +            android:textStyle="bold"
+

2020-10-26 16:50 UTC, raxander67 commented on app/src/main/res/layout/list_item_movie.xml
> +            android:paddingRight="16dp"
done

2020-10-26 16:52 UTC, raxander67 commented on app/src/main/res/layout/list_item_movie.xml
> +        android:layout_height="35dp"
done

2020-10-26 16:52 UTC, raxander67 commented on app/src/main/res/layout/list_item_movie.xml
> +    android:minHeight="72dp"
? done +-

2020-10-26 17:50 UTC, merged

2020-10-26 20:55 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +        return {
Тут лучше написать по-другому.
1) Не совсем ясно зачем этой функции такое возвращаемое значение
2) Лучше разделять данные и работу с view
Можно было бы сделать так:
Создать метод, который на вход принимал бы строку, и список фильмов а на выходе возвращал бы список например MainCardContainer
А потом уже это список из MainCardContainer передавать в adapter.

Просто тут идёт и создание MainСardContainer и передача этого в adapter. В целом лучше методы разделять. Чтобы были методы работающие с данными и методы которые передают эти данные во вью

2020-10-26 20:56 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +        return {
Таким образом, потом можно было бы использовать этот маппер везде

2020-10-26 20:57 UTC, AndroidStudentClub commented on app/src/main/java/ru/rakhman/moviefinder/ui/tvshows/TvShowsFragment.kt
> +        return {
То есть можно было бы создать object MainCardContainerMapper{
         toItems(string,list:List<Movie>):List<MainCardContainer>
} и потом его использовать